### ISSUE TITLE
all link buttons are not displayed in header section

### ISSUE THREAD

**Issue by laurima** [wimmalab/wimmalab.github.io#1]
OS: ubuntu mate 16.10
client: 53.0.2 (64-bit) for Ubuntu canonical-1.0
screen width: 300px-1366px

Only button link to Old Challenge Factry is displayed.
Other buttons are not visible.

**Comment by AVeselovski** [comment]
That is a very specific bug, impossible to replicate on my end. Perhaps not a big priority right now?
